nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true 
clone_depth: 1
test: off
deploy: off
environment:
  global:
    AZURE_ACCOUNT:
      secure: FYmVXjX2D5Em6RojfxM6aQ==
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
install:
  - ps: .\download_artifacts.ps1
build_script:
  - build.cmd -BuildQuality alpha -OsxZip binaries/osx-x64.zip -LinuxZip binaries/linux-x64.zip
artifacts:
  - path: 'artifacts\build\*.nupkg'